export const FRAUD_GET_STARTED = 'FRAUD_GET_STARTED';
export const FRAUD_GET_FINISHED = 'FRAUD_GET_FINISHED';
export const FRAUD_GET_ERROR = 'FRAUD_GET_ERROR';
export const FRAUD_SET_DATE = 'FRAUD_SET_DATE';
