export const REPORTS_GET_STARTED = 'REPORTS_GET_STARTED';
export const REPORTS_GET_FINISHED = 'REPORTS_GET_FINISHED';
export const REPORTS_GET_ERROR = 'REPORTS_GET_ERROR';
export const REPORTS_NEXT_PAGE = 'REPORTS_NEXT_PAGE';
export const REPORTS_PREV_PAGE = 'REPORTS_PREV_PAGE';
export const REPORTS_FIRST_PAGE = 'REPORTS_FIRST_PAGE';
export const REPORTS_SET_TYPE = 'REPORTS_SET_TYPE';
