export const STATS_GET_STARTED = 'STATS_GET_STARTED';
export const STATS_GET_FINISHED = 'STATS_GET_FINISHED';
export const STATS_GET_ERROR = 'STATS_GET_ERROR';
export const STATS_SET_DATE = 'STATS_SET_DATE';
export const STATS_SET_CURRENT_ACCOUNTS = 'STATS_SET_CURRENT_ACCOUNTS';
export const STATS_GET_ACCOUNTS_FINISHED = 'STATS_GET_ACCOUNTS_FINISHED';
